"""Page: About / Architecture"""
import sys, os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..'))

import streamlit as st
from services.api_client import BACKEND_BASE_URL

st.set_page_config(page_title="About & Architecture", page_icon="📖", layout="wide")
st.title("📖 About & Architecture")

st.markdown(f"""
## Ore Beneficiation Plant Digital Twin

This application is a **software digital twin** of a typical iron ore beneficiation plant flowsheet.
It provides interactive simulation, visualization, and analytics for process monitoring and decision support.

> ⚠️ **DEMO / SIMULATION** — All values are generated by a deterministic simulation engine.  
> This is **not** a validated process-control system. Do not use for live plant control without engineering validation.

---

## 🏗️ Software Architecture

```
┌─────────────────────────────────────────────────────────┐
│         mining-digital-twin-frontend (Streamlit)        │
│  ┌──────────┐ ┌──────────┐ ┌──────────┐ ┌───────────┐  │
│  │ Home /   │ │ 3D Twin  │ │Equipment │ │Simulation │  │
│  │ Overview │ │(Three.js)│ │ Details  │ │Analytics  │  │
│  └────┬─────┘ └────┬─────┘ └────┬─────┘ └─────┬─────┘  │
│       └────────────┴────────────┴─────────────┘         │
│              services/api_client.py (HTTPS REST)        │
└───────────────────────┬─────────────────────────────────┘
                        │ BACKEND_BASE_URL = {BACKEND_BASE_URL}
┌───────────────────────▼─────────────────────────────────┐
│         mining-digital-twin-backend (FastAPI/Render)    │
│  ┌──────────────────────────────────────────────────┐   │
│  │  /health  /api/v1/plant  /equipment  /streams    │   │
│  │  /simulation  /analytics  /optimization          │   │
│  │  /data-quality                                   │   │
│  └──────────────────────────────────────────────────┘   │
│  ┌────────────┐ ┌───────────────┐ ┌──────────────────┐  │
│  │ Simulation │ │ Mass Balance  │ │ Mock/Demo Data   │  │
│  │  Engine    │ │    Service    │ │ (seed_data.py)   │  │
│  └────────────┘ └───────────────┘ └──────────────────┘  │
│  Pydantic Schemas │ CORS │ Logging │ render.yaml        │
└─────────────────────────────────────────────────────────┘
```

---

## 🔄 Process Represented

The flowsheet follows this topology:

**ROM Ore → Primary Crusher (CR-001) → Vibrating Screen (SC-001)**  
↳ Oversize → Secondary Crusher (CR-002) → Rotary Scrubber (RS-001)  
↳ Undersize/Lump → Rotary Scrubber (RS-001)  
↓  
**Jig Concentrator 1 (JG-001)**  
↳ Concentrate → Spiral Classifier (SP-001) → Hydrocyclone (HC-001) → WHIMS (WHIMS-001)  
  ↳ Pellet Concentrate ← WHIMS  
  ↳ Middlings → Tertiary Crusher (CR-003) → Screen (SC-002) → Jig 2 (JG-002) → Shaking Table (TB-001)  
    ↳ Ore Fines, Middlings products  
↳ Tailings → Tailings disposal  

---

## 📦 Equipment IDs (Stable)

| ID | Name | Type |
|----|------|------|
| CR-001 | Primary Jaw Crusher | PrimaryCrusher |
| SC-001 | Primary Vibrating Screen | VibratingScreen |
| CR-002 | Secondary Cone Crusher | SecondaryCrusher |
| RS-001 | Rotary Scrubber | RotaryScrubber |
| JG-001 | Jig Concentrator 1 | Jig |
| SP-001 | Spiral Classifier | SpiralClassifier |
| HC-001 | Hydrocyclone Cluster | Hydrocyclone |
| WHIMS-001 | Wet HI Magnetic Separator | MagneticSeparator |
| CR-003 | Tertiary VSI Crusher | TertiaryCrusher |
| SC-002 | Tertiary Vibrating Screen | VibratingScreen |
| JG-002 | Jig Concentrator 2 | Jig |
| TB-001 | Shaking Water Table | ShakingTable |

---

## ⚠️ Assumptions & Limitations

1. **Mass split factors** are configurable estimates — not validated plant data.
2. **Equipment parameters** (CSS, pressures, speeds) are representative defaults.
3. **Simulation engine** is a deterministic stream-propagation model, not a physics-based simulator.
4. No live PLC/SCADA/OPC-UA integration in this demo.
5. **Fixed random seed (42)** ensures reproducibility of DEMO data.

---

## 🚀 Deployment

| Component | Technology | Hosting |
|-----------|-----------|---------|
| Frontend | Streamlit + Three.js | Streamlit Community Cloud |
| Backend | FastAPI + Uvicorn | Render Web Service |
| Data | In-memory (SQLite-ready) | Backend state store |

**Backend start command:** `uvicorn app.main:app --host 0.0.0.0 --port $PORT`  
**Health check:** `GET /health`  
**Backend URL configured via:** `BACKEND_BASE_URL` env var / Streamlit secrets  

---

## 📋 Engineering Boundary

This digital twin is a software/simulation representation only.  
Before any live plant control or recommendation, the following are mandatory:  
- Real plant historian/PLC/SCADA data  
- Engineering constraints and equipment limits  
- Instrument validation and process-model calibration  
- Cybersecurity assessment  
- Domain-expert approval  
""")
